name: Compare Files across two Branches
on:
    workflow_dispatch:
jobs:
    GET_Branches_To_Compare:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Get Branches
              run: |
                  sh scripts/shellScripts/getBranches.sh dev main
                  echo "source_branch: ${{ env.SOURCE_BRANCH }}"
                  echo "target_branch: ${{ env.TARGET_BRANCH }}"
            - name: Checkout Source Branch Code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                repository: Somanath-Inc/GitHubActionsDec14
                path: SourceBranchPath
                ref: ${{env.SOURCE_BRANCH}}
            - name: Checkout Target Branch Code
              uses: actions/checkout@v3
              with:
                  repository: Somanath-Inc/GitHubActionsDec14
                  path: TargetBranchPath
                  ref: ${{ env.TARGET_BRANCH }}
            - name: Display Branches
              run: |
                  sh scripts/shellScripts/getBranches.sh Dev Main
                  echo "source_branch: ${{ env.SOURCE_BRANCH }}"
                  echo "target_branch: ${{ env.TARGET_BRANCH }}"
            - name: Get list of files to compare
              run: |
                    sh scripts/shellScripts/iterate.sh SourceBranchPath
